#!/bin/bash -e

file1=comm.test.$1.$2.a
file2=comm.test.$1.$2.b

rm -f $file1 $file2 $file1.sort $file2.sort

for ((  i = 0 ;  i < $1;  i++  ))
do
	for (( j = 0 ; j < $2 ; j++ ))
	do
		x=`echo $(( $RANDOM % 10 ))`
		echo -n $x >> $file1
		x=`echo $(( $RANDOM % 10 ))`
                echo -n $x >> $file2
	done
	echo "" >> $file1
	echo "" >> $file2
done

sort -u $file1 > $file1.sort
sort -u $file2 > $file2.sort
rm -f $file1 $file2
